[platformio]
default_envs = nodemcuv2
data_dir = data

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
board_build.filesystem = littlefs
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    tzapu/WiFiManager@^2.0.15-rc.1
    bblanchon/ArduinoJson@^6.21.3
    links2004/WebSockets@^2.4.1
    adafruit/DHT sensor library@^1.4.4
    adafruit/Adafruit Unified Sensor@^1.1.9

[env:native]
platform = native
test_build_src = true
